/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author pipem
 */
public class InterCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form Compra
     */
    public InterCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldSaldo = new javax.swing.JTextField();
        SALDO = new javax.swing.JLabel();
        jLabelNrocuenta = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        jTextapellido = new javax.swing.JTextField();
        jTextcedula = new javax.swing.JTextField();
        jTextdireccion = new javax.swing.JTextField();
        jButtonComprar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonVOLVER = new javax.swing.JButton();
        jButtonELIMINAR = new javax.swing.JButton();
        jButtonEDITAR = new javax.swing.JButton();
        jLabelwallpaper = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 100, -1));

        SALDO.setText("SALDO");
        jPanel1.add(SALDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabelNrocuenta.setText("No.Cuenta");
        jPanel1.add(jLabelNrocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 110, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 100, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 260, 30));
        jPanel1.add(jTextapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 240, 30));
        jPanel1.add(jTextcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 230, 30));
        jPanel1.add(jTextdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 300, 30));

        jButtonComprar.setText("COMPRAR");
        jPanel1.add(jButtonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 100, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "PEDIDO", "MONTO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 460, 250));

        jButtonVOLVER.setText("VOLVER");
        jButtonVOLVER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVOLVERActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 610, 100, -1));

        jButtonELIMINAR.setText("ELIMINAR");
        jPanel1.add(jButtonELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 670, 100, -1));

        jButtonEDITAR.setText("EDITAR");
        jPanel1.add(jButtonEDITAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 730, 100, -1));

        jLabelwallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 4.jpg"))); // NOI18N
        jPanel1.add(jLabelwallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSaldoActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButtonVOLVERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVOLVERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVOLVERActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel SALDO;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JButton jButtonEDITAR;
    private javax.swing.JButton jButtonELIMINAR;
    private javax.swing.JButton jButtonVOLVER;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelNrocuenta;
    private javax.swing.JLabel jLabelwallpaper;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldSaldo;
    private javax.swing.JTextField jTextapellido;
    private javax.swing.JTextField jTextcedula;
    private javax.swing.JTextField jTextdireccion;
    // End of variables declaration//GEN-END:variables
}
